region                  = "us-west-2"
s3_bucket_name          = "my-dev-bucket"
ec2_instance_name       = "dev-ec2-instance"
ec2_instance_type       = "t2.micro"
parameter_store_db_name = "/dev/db_name"
parameter_store_db_user = "/dev/db_user"
db_name                 = "dev_database"
db_user                 = "dev_user"